behaviors:
  PushBlock:
    hyperparameters:
      batch_size: 660
      beta: 0.01
      buffer_size: 12577
      epsilon: 0.3
      lambd: 0.99
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 6
    keep_checkpoints: 5
    max_steps: 50000
    network_settings:
      hidden_units: 342
      normalize: false
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 0.5
    summary_freq: 4085
    time_horizon: 30
    trainer_type: ppo
