behaviors:
  PushBlock:
    hyperparameters:
      batch_size: 592
      beta: 0.01
      buffer_size: 8777
      epsilon: 0.3
      lambd: 0.99
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 5
    keep_checkpoints: 5
    max_steps: 50000
    network_settings:
      hidden_units: 399
      normalize: false
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 0.5
    summary_freq: 880
    time_horizon: 88
    trainer_type: ppo
